services:
  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/config:/etc/caddy
      - ./build:/srv/app
      - ./media:/srv/media
